using Microsoft.EntityFrameworkCore;

namespace JhaylaPlusAPI.Models
{
    public class PeliculasDbContext : DbContext
    {
        public DbSet<Peliculas> Peliculas { get; set; }

        public PeliculasDbContext(DbContextOptions<PeliculasDbContext> options)
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Peliculas>().HasData(
                new Peliculas { Id = 1, Titulo = "Nuestro hilo rojo a distancia", ImagenUrl = "/images/ojitoscute.png", Year = 2026, Sinopsis = "Dos jóvenes que se conocieron por internet sostienen una relación a distancia mientras enfrentan la duda de si algún día podrán encontrarse en persona. Una historia intimista sobre la paciencia, los mensajes de texto a medianoche y el amor que resiste el tiempo y la distancia.", Duracion = "52m", Director = "Camila Duarte", Genero = "Romance, Drama", Reparto = "Valeria Ospina, Martín Reyes, Daniela Cortés", Clasificacion = "12+", Formatos = "HD, 5.1, CC", Etiqueta = "Original Jhayla+" },
                new Peliculas { Id = 2, Titulo = "Avengers Doomsday", ImagenUrl = "https://m.media-amazon.com/images/M/MV5BNGEwYWZkN2UtOTQ5Mi00MGQzLWEzNjYtMWMyNDBkMTkzMWNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", Year = 2026, Sinopsis = "Un equipo de héroes debe unir fuerzas por última vez para enfrentar una amenaza capaz de borrar el mundo tal como lo conocen. Alianzas viejas se ponen a prueba mientras el destino del planeta pende de un hilo.", Duracion = "2h 21m", Director = "Adrián Salcedo", Genero = "Acción, Aventura, Ciencia ficción", Reparto = "Bruno Estrada, Naomi Vidal, Tomás Ferreira, Lucía Mendoza", Clasificacion = "12+", Formatos = "HD, 5.1, CC", Etiqueta = "Estreno" },
                new Peliculas { Id = 3, Titulo = "Spiderman", ImagenUrl = "https://assets.cinemark-core.com/5db771be04daec00076df3f5/vista/movies/6a22d1b9720d1d2a7f8d9a19/common/spiderman-nuevo-dia-109320-1780678232870", Year = 2026, Sinopsis = "Un joven héroe enmascarado debe proteger su ciudad de una nueva amenaza mientras intenta equilibrar su vida personal con la responsabilidad de llevar el traje. Acción trepidante entre los rascacielos y decisiones que lo marcarán para siempre.", Duracion = "2h 08m", Director = "Renata Falcón", Genero = "Acción, Aventura, Superhéroes", Reparto = "Iker Salazar, Camila Rentería, Diego Guzmán", Clasificacion = "12+", Formatos = "HD, 5.1, CC", Etiqueta = "Tendencia" },
                new Peliculas { Id = 4, Titulo = "It", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkmVRJ71XkUcnm_DAc2_d4_Iw9oX6bqu9lIY4Zz9a9ZlLOCDINM4dnX0zj&s=10", Year = 2017, Sinopsis = "En un pequeño pueblo, un grupo de niños se enfrenta a una entidad ancestral que se alimenta del miedo y toma la forma de sus peores pesadillas. Una historia de terror y amistad a partes iguales.", Duracion = "2h 15m", Director = "Howard Steiner", Genero = "Terror, Suspenso", Reparto = "Simon Wade, Charlotte Byrne, Milo Kagan", Clasificacion = "15+", Formatos = "HD, 5.1, CC", Etiqueta = "Terror Pop" },
                new Peliculas { Id = 5, Titulo = "Moana", ImagenUrl = "https://static.wikia.nocookie.net/disney/images/7/76/Moana_official_poster.jpg/revision/latest?cb=20160921035605&path-prefix=es", Year = 2016, Sinopsis = "La hija de un jefe tribal se embarca en un viaje por el océano para salvar a su pueblo, guiada por la fuerza del mar y la ayuda de un semidiós algo arrogante. Aventura, música y descubrimiento personal en altamar.", Duracion = "1h 47m", Director = "Estudios Costa Azul", Genero = "Animación, Aventura, Familia", Reparto = "Voces originales: Malia Kealoha, James Nuanez", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Familiar" },
                new Peliculas { Id = 6, Titulo = "Son como niños 2", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7zjfqxpuf0AHiQ-y2EvPuNku-JVcGZH2-_puckCF_sRdwbiKGdeF2tcqs&s=10", Year = 2013, Sinopsis = "Un grupo de amigos de toda la vida se reúne otra vez de vacaciones junto a sus familias, y el caos y las bromas están garantizados. Una comedia ligera sobre la amistad, la nostalgia y las vacaciones que nunca salen como se planean.", Duracion = "1h 41m", Director = "Gary Feldstein", Genero = "Comedia, Familia", Reparto = "Dennis Kohler, Marco Rubbio, Salma Trent", Clasificacion = "12+", Formatos = "HD, 5.1, CC", Etiqueta = "Comedia" },
                new Peliculas { Id = 7, Titulo = "The last house", ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMjI5YTQ3YmItZjk1ZS00ZDBmLWJhZDMtNThhMDI5ZTRkMTcxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", Year = 2026, Sinopsis = "Una familia se muda a una casa aislada con un pasado oscuro, sin saber que algo dentro de sus paredes lleva años esperando compañía. El terror psicológico se apodera de cada rincón de su nuevo hogar.", Duracion = "1h 38m", Director = "Wren Ashdown", Genero = "Terror, Suspenso", Reparto = "Ivy Callahan, Noah Prescott, Elias Vance", Clasificacion = "15+", Formatos = "HD, 5.1, CC", Etiqueta = "Próximamente" },
                new Peliculas { Id = 8, Titulo = "Un chihuahua en Beverly Hills", ImagenUrl = "https://es.web.img2.acsta.net/medias/nmedia/18/68/79/58/19045139.jpg", Year = 2008, Sinopsis = "Una pequeña chihuahua acostumbrada al lujo de Beverly Hills se pierde durante un viaje y debe encontrar el camino de regreso a casa junto a nuevos e inesperados amigos.", Duracion = "1h 31m", Director = "Rosa Delgadillo", Genero = "Comedia, Familia", Reparto = "Voces originales: Andy García, Paz Vega", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Infantil" },
                new Peliculas { Id = 9, Titulo = "Cenicienta", ImagenUrl = "https://es.web.img2.acsta.net/pictures/14/11/19/16/01/398307.jpg", Year = 2015, Sinopsis = "La versión en imagen real del clásico cuento de hadas: una joven bondadosa soporta el maltrato de su madrastra hasta que la magia y un baile real cambian su destino para siempre.", Duracion = "1h 45m", Director = "Alicia Montfort", Genero = "Fantasía, Romance, Familia", Reparto = "Elle Sinclair, Cate Ashworth, Robert Hale", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Clásico" },
                new Peliculas { Id = 10, Titulo = "Rapunzel", ImagenUrl = "https://es.web.img3.acsta.net/medias/nmedia/18/79/96/30/19541005.jpg", Year = 2010, Sinopsis = "Una princesa de cabello mágico y extraordinariamente largo escapa de la torre donde ha vivido encerrada toda su vida, junto a un carismático forajido, para descubrir por fin el mundo exterior.", Duracion = "1h 40m", Director = "Estudios Corona Real", Genero = "Animación, Fantasía, Familia", Reparto = "Voces originales: Mandy Halloway, Zack Levinson", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Aventura Mágica" },
                new Peliculas { Id = 11, Titulo = "Cars: Una aventura sobre ruedas", ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTg5NzY0MzA2MV5BMl5BanBnXkFtZTYwNDc3NTc2._V1_FMjpg_UX1000_.jpg", Year = 2006, Sinopsis = "Un joven auto de carreras arrogante queda varado en un pequeño pueblo de la Ruta 66 y aprende, entre sus excéntricos habitantes, el verdadero significado de la amistad y la humildad.", Duracion = "1h 57m", Director = "Estudios Ruta 66", Genero = "Animación, Familia, Deportes", Reparto = "Voces originales: Owen McQueen, Larry Hudson", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Favorita" },
                new Peliculas { Id = 12, Titulo = "Toy Story", ImagenUrl = "https://es.web.img3.acsta.net/pictures/14/03/17/10/20/509771.jpg", Year = 1995, Sinopsis = "Un vaquero de juguete ve amenazado su lugar como el favorito de su dueño con la llegada de una moderna figura de acción espacial. Juntos deberán aprender a trabajar en equipo para volver a casa.", Duracion = "1h 21m", Director = "Estudios Lámpara Amarilla", Genero = "Animación, Familia, Aventura", Reparto = "Voces originales: Tom Halbert, Timothy Allan", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Imperdible" },
                new Peliculas { Id = 13, Titulo = "La bella y la bestia", ImagenUrl = "https://es.web.img3.acsta.net/pictures/17/01/09/09/56/256507.jpg", Year = 2017, Sinopsis = "Versión en imagen real del clásico cuento: una joven inteligente y curiosa es retenida en un castillo encantado por una bestia con apariencia aterradora pero un corazón que aprende a abrirse.", Duracion = "2h 09m", Director = "Constance Fielding", Genero = "Fantasía, Romance, Musical", Reparto = "Emmeline Rousse, Daniel Ashcombe, Ludovic Marchetti", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Musical" },
                new Peliculas { Id = 14, Titulo = "La princesa y el sapo", ImagenUrl = "https://m.media-amazon.com/images/M/MV5BOTE3YTExYTEtOTUxZC00OTM0LWJmYmItMDk5YjczNmIwNzA2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", Year = 2009, Sinopsis = "Una joven trabajadora y soñadora de Nueva Orleans se convierte en rana tras un beso inesperado, y junto a un príncipe hechizado emprende una aventura mágica por los pantanos.", Duracion = "1h 37m", Director = "Estudios Pantano Dulce", Genero = "Animación, Fantasía, Musical", Reparto = "Voces originales: Anika Noni Rose, Bruno Campos", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Aclamada" },
                new Peliculas { Id = 15, Titulo = "Malefica", ImagenUrl = "https://es.web.img3.acsta.net/pictures/14/03/11/09/33/450247.jpg", Year = 2014, Sinopsis = "La verdadera historia detrás del hada oscura: una traición en su juventud despierta una maldición que lanza sobre un reino entero, hasta que una niña inocente pone a prueba su corazón endurecido.", Duracion = "1h 37m", Director = "Rowena Ashcroft", Genero = "Fantasía, Aventura", Reparto = "Ainsley Deveraux, Elle Fanshawe, Sam Riordan", Clasificacion = "12+", Formatos = "HD, 5.1, CC", Etiqueta = "Fantasía" },
                new Peliculas { Id = 16, Titulo = "Malefica 2", ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/5/56/MLFCDMCartel.jpg/revision/latest?cb=20190927034818&path-prefix=es", Year = 2019, Sinopsis = "Con el compromiso real en puerta, viejas tensiones entre humanos y criaturas mágicas resurgen, obligando al hada oscura a decidir hasta dónde llegar para proteger a quienes ama.", Duracion = "1h 59m", Director = "Rowena Ashcroft", Genero = "Fantasía, Aventura", Reparto = "Ainsley Deveraux, Elle Fanshawe, Marguerite Colt", Clasificacion = "12+", Formatos = "HD, 5.1, CC", Etiqueta = "Secuela" },
                new Peliculas { Id = 17, Titulo = "La sirenita", ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/6/6f/28a.jpg/revision/latest/scale-to-width-down/1200?cb=20200812013209&path-prefix=es", Year = 1989, Sinopsis = "Una joven sirena fascinada por el mundo humano hace un trato peligroso con una bruja del mar a cambio de piernas y la oportunidad de vivir en tierra firme.", Duracion = "1h 23m", Director = "Estudios Arrecife de Coral", Genero = "Animación, Fantasía, Musical", Reparto = "Voces originales: Jodi Benson, Pat Carroll", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Clásico Animado" },
                new Peliculas { Id = 18, Titulo = "La sirenita 2", ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/1/1c/La_Sirenita_2.jpg/revision/latest?cb=20091112103319&path-prefix=es", Year = 2026, Sinopsis = "Años después de dejar el mar, la hija de la sirena debe redescubrir su propia conexión con el océano cuando un viejo peligro familiar regresa a amenazar su hogar en tierra.", Duracion = "1h 15m", Director = "Estudios Arrecife de Coral", Genero = "Animación, Fantasía, Musical", Reparto = "Voces originales: Jodi Benson, Tara Strong", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Próximamente" },
                new Peliculas { Id = 19, Titulo = "The silent", ImagenUrl = "https://m.media-amazon.com/images/M/MV5BYzY2ZjM0NTgtNDc3OS00YmQwLTlkN2YtMmRmMDAxMmM0NTliXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", Year = 2019, Sinopsis = "En una casa donde el más mínimo sonido puede significar el fin, una familia debe aprender a comunicarse en absoluto silencio para sobrevivir a una presencia que acecha en la oscuridad.", Duracion = "1h 30m", Director = "Marcus Thorne", Genero = "Terror, Suspenso", Reparto = "Ellery Voss, Grant Halliwell, Priya Anand", Clasificacion = "15+", Formatos = "HD, 5.1, CC", Etiqueta = "Suspenso" },
                new Peliculas { Id = 20, Titulo = "Un lugar en silencio dia 1", ImagenUrl = "https://m.media-amazon.com/images/S/pv-target-images/450fc3671402b95549e29af286cf9c6c4aa439e2a2399adbde570f2970c6092a._UR2000,3000_.jpg", Year = 2018, Sinopsis = "El relato de las primeras horas de una invasión silenciosa: una ciudad entera aprende, de la forma más brutal, que hacer ruido puede costarle la vida a cualquiera.", Duracion = "1h 39m", Director = "Marcus Thorne", Genero = "Terror, Suspenso, Ciencia ficción", Reparto = "Grant Halliwell, Priya Anand, Owen Castellanos", Clasificacion = "15+", Formatos = "HD, 5.1, CC", Etiqueta = "Éxito" },
                new Peliculas { Id = 21, Titulo = "No se desea buena suerte", ImagenUrl = "https://pics.filmaffinity.com/don_t_say_good_luck-469823819-large.jpg", Year = 2026, Sinopsis = "Una racha de sucesos cada vez más inquietantes convence a una mujer de que la suerte, buena o mala, se puede heredar como una maldición familiar que ahora le toca romper.", Duracion = "1h 46m", Director = "Selene Kowalski", Genero = "Suspenso, Drama", Reparto = "Nadia Ferro, Julián Vasconcelos, Marina Estep", Clasificacion = "15+", Formatos = "HD, 5.1, CC", Etiqueta = "Novedad" },
                new Peliculas { Id = 22, Titulo = "La captura", ImagenUrl = "https://m.media-amazon.com/images/M/MV5BOGJkNjBkNTUtYWM2OC00MDJiLWE0ZjctMmMxMjE1ODMxMzQxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", Year = 2026, Sinopsis = "Un detective obsesionado con un caso sin resolver se acerca peligrosamente a la verdad, solo para descubrir que atrapar al culpable puede costarle todo lo que ama.", Duracion = "1h 52m", Director = "Ibrahim Castell", Genero = "Suspenso, Drama, Crimen", Reparto = "Renata Ibarra, Tomás Aldunate, Greta Solheim", Clasificacion = "15+", Formatos = "HD, 5.1, CC", Etiqueta = "Policial" },
                new Peliculas { Id = 23, Titulo = "La nueva cenicienta", ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/e/e9/LaNuevaCenicienta_Poster.png/revision/latest?cb=20190818235855&path-prefix=es", Year = 2004, Sinopsis = "Una estudiante que trabaja en el restaurante familiar sueña con salir de su pequeño pueblo, y encuentra en un chat anónimo con un compañero de escuela la esperanza de un futuro distinto.", Duracion = "1h 35m", Director = "Priscilla Nkemelu", Genero = "Comedia, Romance", Reparto = "Holly Marchbanks, Cody Trentham, Bianca Suárez", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Romance" },
                new Peliculas { Id = 24, Titulo = "La nueva cenicienta 2", ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTUwNDAzMzIxOF5BMl5BanBnXkFtZTgwNTU1NzAwNzE@._V1_FMjpg_UX1000_.jpg", Year = 2008, Sinopsis = "Una nueva generación revive el cuento moderno de Cenicienta: una chica trabajadora usa un alias en línea para perseguir sus sueños, sin imaginar a quién va a encontrar del otro lado.", Duracion = "1h 30m", Director = "Priscilla Nkemelu", Genero = "Comedia, Romance", Reparto = "Holly Marchbanks, Devon Ashworth, Bianca Suárez", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Juvenil" },
                new Peliculas { Id = 25, Titulo = "Charlie y la fábrica de chocolate", ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTAxMGFjODItYTliNy00NjQyLTlkM2MtYWY5YzVmYjk5OGFiXkEyXkFqcGc@._V1_.jpg", Year = 2005, Sinopsis = "Un niño de escasos recursos gana un boleto dorado para visitar la fábrica de chocolates más misteriosa del mundo, dirigida por un excéntrico e impredecible chocolatero.", Duracion = "1h 55m", Director = "Desmond Aldwych", Genero = "Fantasía, Familia, Musical", Reparto = "Warrick Feathering, Ida Loncar, Percy Whitmore", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Imperdible" },
                new Peliculas { Id = 26, Titulo = "Pelé", ImagenUrl = "https://hips.hearstapps.com/hmg-prod/images/pele-dcumental-netflix-esquire2-1613895136.jpg", Year = 2021, Sinopsis = "Un repaso documental a la vida de uno de los futbolistas más influyentes de la historia, desde su infancia humilde hasta convertirse en leyenda del deporte a nivel global.", Duracion = "1h 47m", Director = "Documental Colectivo Sur", Genero = "Documental, Biografía, Deportes", Reparto = "Con la participación de figuras del fútbol mundial", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Documental" },
                new Peliculas { Id = 27, Titulo = "Una casa patas arriba", ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTIwMDQyNjQzNl5BMl5BanBnXkFtZTcwMjEwODI0MQ@@._V1_.jpg", Year = 2007, Sinopsis = "Cuando una familia se muda a una nueva ciudad, su casa parece tener vida propia y decide literalmente ponerlo todo patas arriba, generando una serie de enredos tan caóticos como divertidos.", Duracion = "1h 32m", Director = "Winona Halbrook", Genero = "Comedia, Familia", Reparto = "Desmond Pratchett, Ainsley Marek, Cora Bellweather", Clasificacion = "TP", Formatos = "HD, 5.1, CC", Etiqueta = "Comedia" }
            );
        }
    }
}