// <auto-generated />
using JhaylaPlusAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JhaylaPlusAPI.Migrations
{
    [DbContext(typeof(PeliculasDbContext))]
    [Migration("20260830183616_ArreglarImagenes")]
    partial class ArreglarImagenes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JhaylaPlusAPI.Models.Peliculas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagenUrl = "/images/ojitoscute.png",
                            Titulo = "Nuestro hilo rojo a distancia",
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BNGEwYWZkN2UtOTQ5Mi00MGQzLWEzNjYtMWMyNDBkMTkzMWNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Titulo = "Avengers Doomsday",
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            ImagenUrl = "https://assets.cinemark-core.com/5db771be04daec00076df3f5/vista/movies/6a22d1b9720d1d2a7f8d9a19/common/spiderman-nuevo-dia-109320-1780678232870",
                            Titulo = "Spiderman",
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkmVRJ71XkUcnm_DAc2_d4_Iw9oX6bqu9lIY4Zz9a9ZlLOCDINM4dnX0zj&s=10",
                            Titulo = "It",
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            ImagenUrl = "https://static.wikia.nocookie.net/disney/images/7/76/Moana_official_poster.jpg/revision/latest?cb=20160921035605&path-prefix=es",
                            Titulo = "Moana",
                            Year = 2016
                        },
                        new
                        {
                            Id = 6,
                            ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7zjfqxpuf0AHiQ-y2EvPuNku-JVcGZH2-_puckCF_sRdwbiKGdeF2tcqs&s=10",
                            Titulo = "Son como niños 2",
                            Year = 2013
                        },
                        new
                        {
                            Id = 7,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMjI5YTQ3YmItZjk1ZS00ZDBmLWJhZDMtNThhMDI5ZTRkMTcxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Titulo = "The last house",
                            Year = 2026
                        },
                        new
                        {
                            Id = 8,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+08",
                            Titulo = "Pelicula placeholder 08",
                            Year = 2026
                        },
                        new
                        {
                            Id = 9,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+09",
                            Titulo = "Pelicula placeholder 09",
                            Year = 2026
                        },
                        new
                        {
                            Id = 10,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+10",
                            Titulo = "Pelicula placeholder 10",
                            Year = 2026
                        },
                        new
                        {
                            Id = 11,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+11",
                            Titulo = "Pelicula placeholder 11",
                            Year = 2026
                        },
                        new
                        {
                            Id = 12,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+12",
                            Titulo = "Pelicula placeholder 12",
                            Year = 2026
                        },
                        new
                        {
                            Id = 13,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+13",
                            Titulo = "Pelicula placeholder 13",
                            Year = 2026
                        },
                        new
                        {
                            Id = 14,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+14",
                            Titulo = "Pelicula placeholder 14",
                            Year = 2026
                        },
                        new
                        {
                            Id = 15,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+15",
                            Titulo = "Pelicula placeholder 15",
                            Year = 2026
                        },
                        new
                        {
                            Id = 16,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+16",
                            Titulo = "Pelicula placeholder 16",
                            Year = 2026
                        },
                        new
                        {
                            Id = 17,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+17",
                            Titulo = "Pelicula placeholder 17",
                            Year = 2026
                        },
                        new
                        {
                            Id = 18,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+18",
                            Titulo = "Pelicula placeholder 18",
                            Year = 2026
                        },
                        new
                        {
                            Id = 19,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+19",
                            Titulo = "Pelicula placeholder 19",
                            Year = 2026
                        },
                        new
                        {
                            Id = 20,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+20",
                            Titulo = "Pelicula placeholder 20",
                            Year = 2026
                        },
                        new
                        {
                            Id = 21,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+21",
                            Titulo = "Pelicula placeholder 21",
                            Year = 2026
                        },
                        new
                        {
                            Id = 22,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+22",
                            Titulo = "Pelicula placeholder 22",
                            Year = 2026
                        },
                        new
                        {
                            Id = 23,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+23",
                            Titulo = "Pelicula placeholder 23",
                            Year = 2026
                        },
                        new
                        {
                            Id = 24,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+24",
                            Titulo = "Pelicula placeholder 24",
                            Year = 2026
                        },
                        new
                        {
                            Id = 25,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+25",
                            Titulo = "Pelicula placeholder 25",
                            Year = 2026
                        },
                        new
                        {
                            Id = 26,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+26",
                            Titulo = "Pelicula placeholder 26",
                            Year = 2026
                        },
                        new
                        {
                            Id = 27,
                            ImagenUrl = "https://placehold.co/400x600/141824/1cd2e5?text=Pelicula+27",
                            Titulo = "Pelicula placeholder 27",
                            Year = 2026
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
