// <auto-generated />
using JhaylaPlusAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JhaylaPlusAPI.Migrations
{
    [DbContext(typeof(PeliculasDbContext))]
    [Migration("20260828115505_SeedPeliculasData")]
    partial class SeedPeliculasData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JhaylaPlusAPI.Models.Peliculas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagenUrl = "/images/ojitoscute.png",
                            Titulo = "Nuestro hilo rojo a distancia",
                            Year = 2024
                        },
                        new
                        {
                            Id = 2,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5B...",
                            Titulo = "Avengers Doomsday",
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            ImagenUrl = "https://assets.cinemark-core.com/5db771be04daec0...",
                            Titulo = "Spiderman",
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ...",
                            Titulo = "It",
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            ImagenUrl = "https://static.wikia.nocookie.net/disney/images/7/76...",
                            Titulo = "Moana",
                            Year = 2016
                        },
                        new
                        {
                            Id = 6,
                            ImagenUrl = "https://encrypted-tbn0.gstatic.com/images...",
                            Titulo = "Son como niños 2",
                            Year = 2013
                        },
                        new
                        {
                            Id = 7,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMjI...",
                            Titulo = "The last house",
                            Year = 2009
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
