// <auto-generated />
using JhaylaPlusAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JhaylaPlusAPI.Migrations
{
    [DbContext(typeof(PeliculasDbContext))]
    partial class PeliculasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JhaylaPlusAPI.Models.Peliculas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagenUrl = "/images/ojitoscute.png",
                            Titulo = "Nuestro hilo rojo a distancia",
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BNGEwYWZkN2UtOTQ5Mi00MGQzLWEzNjYtMWMyNDBkMTkzMWNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Titulo = "Avengers Doomsday",
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            ImagenUrl = "https://assets.cinemark-core.com/5db771be04daec00076df3f5/vista/movies/6a22d1b9720d1d2a7f8d9a19/common/spiderman-nuevo-dia-109320-1780678232870",
                            Titulo = "Spiderman",
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkmVRJ71XkUcnm_DAc2_d4_Iw9oX6bqu9lIY4Zz9a9ZlLOCDINM4dnX0zj&s=10",
                            Titulo = "It",
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            ImagenUrl = "https://static.wikia.nocookie.net/disney/images/7/76/Moana_official_poster.jpg/revision/latest?cb=20160921035605&path-prefix=es",
                            Titulo = "Moana",
                            Year = 2016
                        },
                        new
                        {
                            Id = 6,
                            ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7zjfqxpuf0AHiQ-y2EvPuNku-JVcGZH2-_puckCF_sRdwbiKGdeF2tcqs&s=10",
                            Titulo = "Son como niños 2",
                            Year = 2013
                        },
                        new
                        {
                            Id = 7,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMjI5YTQ3YmItZjk1ZS00ZDBmLWJhZDMtNThhMDI5ZTRkMTcxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Titulo = "The last house",
                            Year = 2026
                        },
                        new
                        {
                            Id = 8,
                            ImagenUrl = "https://es.web.img2.acsta.net/medias/nmedia/18/68/79/58/19045139.jpg",
                            Titulo = "Un chihuahua en Beverly Hills",
                            Year = 2008
                        },
                        new
                        {
                            Id = 9,
                            ImagenUrl = "https://es.web.img2.acsta.net/pictures/14/11/19/16/01/398307.jpg",
                            Titulo = "Cenicienta",
                            Year = 2015
                        },
                        new
                        {
                            Id = 10,
                            ImagenUrl = "https://es.web.img3.acsta.net/medias/nmedia/18/79/96/30/19541005.jpg",
                            Titulo = "Rapunzel",
                            Year = 2010
                        },
                        new
                        {
                            Id = 11,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTg5NzY0MzA2MV5BMl5BanBnXkFtZTYwNDc3NTc2._V1_FMjpg_UX1000_.jpg",
                            Titulo = "Cars: Una aventura sobre ruedas",
                            Year = 2006
                        },
                        new
                        {
                            Id = 12,
                            ImagenUrl = "https://es.web.img3.acsta.net/pictures/14/03/17/10/20/509771.jpg",
                            Titulo = "Toy Story",
                            Year = 1995
                        },
                        new
                        {
                            Id = 13,
                            ImagenUrl = "https://es.web.img3.acsta.net/pictures/17/01/09/09/56/256507.jpg",
                            Titulo = "La bella y la bestia",
                            Year = 2017
                        },
                        new
                        {
                            Id = 14,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BOTE3YTExYTEtOTUxZC00OTM0LWJmYmItMDk5YjczNmIwNzA2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Titulo = "La princesa y el sapo",
                            Year = 2009
                        },
                        new
                        {
                            Id = 15,
                            ImagenUrl = "https://es.web.img3.acsta.net/pictures/14/03/11/09/33/450247.jpg",
                            Titulo = "Malefica",
                            Year = 2014
                        },
                        new
                        {
                            Id = 16,
                            ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/5/56/MLFCDMCartel.jpg/revision/latest?cb=20190927034818&path-prefix=es",
                            Titulo = "Malefica 2",
                            Year = 2019
                        },
                        new
                        {
                            Id = 17,
                            ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/6/6f/28a.jpg/revision/latest/scale-to-width-down/1200?cb=20200812013209&path-prefix=es",
                            Titulo = "La sirenita",
                            Year = 1989
                        },
                        new
                        {
                            Id = 18,
                            ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/1/1c/La_Sirenita_2.jpg/revision/latest?cb=20091112103319&path-prefix=es",
                            Titulo = "La sirenita 2",
                            Year = 2026
                        },
                        new
                        {
                            Id = 19,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BYzY2ZjM0NTgtNDc3OS00YmQwLTlkN2YtMmRmMDAxMmM0NTliXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Titulo = "The silent",
                            Year = 2019
                        },
                        new
                        {
                            Id = 20,
                            ImagenUrl = "https://m.media-amazon.com/images/S/pv-target-images/450fc3671402b95549e29af286cf9c6c4aa439e2a2399adbde570f2970c6092a._UR2000,3000_.jpg",
                            Titulo = "Un lugar en silencio dia 1",
                            Year = 2018
                        },
                        new
                        {
                            Id = 21,
                            ImagenUrl = "https://pics.filmaffinity.com/don_t_say_good_luck-469823819-large.jpg",
                            Titulo = "No se desea buena suerte",
                            Year = 2026
                        },
                        new
                        {
                            Id = 22,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BOGJkNjBkNTUtYWM2OC00MDJiLWE0ZjctMmMxMjE1ODMxMzQxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Titulo = "La captura",
                            Year = 2026
                        },
                        new
                        {
                            Id = 23,
                            ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/e/e9/LaNuevaCenicienta_Poster.png/revision/latest?cb=20190818235855&path-prefix=es",
                            Titulo = "La nueva cenicienta",
                            Year = 2004
                        },
                        new
                        {
                            Id = 24,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTUwNDAzMzIxOF5BMl5BanBnXkFtZTgwNTU1NzAwNzE@._V1_FMjpg_UX1000_.jpg",
                            Titulo = "La nueva cenicienta 2",
                            Year = 2008
                        },
                        new
                        {
                            Id = 25,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTAxMGFjODItYTliNy00NjQyLTlkM2MtYWY5YzVmYjk5OGFiXkEyXkFqcGc@._V1_.jpg",
                            Titulo = "Charlie y la fábrica de chocolate",
                            Year = 2005
                        },
                        new
                        {
                            Id = 26,
                            ImagenUrl = "https://hips.hearstapps.com/hmg-prod/images/pele-dcumental-netflix-esquire2-1613895136.jpg",
                            Titulo = "Pelé",
                            Year = 2021
                        },
                        new
                        {
                            Id = 27,
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTIwMDQyNjQzNl5BMl5BanBnXkFtZTcwMjEwODI0MQ@@._V1_.jpg",
                            Titulo = "Una casa patas arriba",
                            Year = 2007
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
