// <auto-generated />
using JhaylaPlusAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JhaylaPlusAPI.Migrations
{
    [DbContext(typeof(PeliculasDbContext))]
    partial class PeliculasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JhaylaPlusAPI.Models.Peliculas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clasificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etiqueta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formatos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reparto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sinopsis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clasificacion = "12+",
                            Director = "Camila Duarte",
                            Duracion = "52m",
                            Etiqueta = "Original Jhayla+",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Romance, Drama",
                            ImagenUrl = "/images/ojitoscute.png",
                            Reparto = "Valeria Ospina, Martín Reyes, Daniela Cortés",
                            Sinopsis = "Dos jóvenes que se conocieron por internet sostienen una relación a distancia mientras enfrentan la duda de si algún día podrán encontrarse en persona. Una historia intimista sobre la paciencia, los mensajes de texto a medianoche y el amor que resiste el tiempo y la distancia.",
                            Titulo = "Nuestro hilo rojo a distancia",
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            Clasificacion = "12+",
                            Director = "Adrián Salcedo",
                            Duracion = "2h 21m",
                            Etiqueta = "Estreno",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Acción, Aventura, Ciencia ficción",
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BNGEwYWZkN2UtOTQ5Mi00MGQzLWEzNjYtMWMyNDBkMTkzMWNkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Reparto = "Bruno Estrada, Naomi Vidal, Tomás Ferreira, Lucía Mendoza",
                            Sinopsis = "Un equipo de héroes debe unir fuerzas por última vez para enfrentar una amenaza capaz de borrar el mundo tal como lo conocen. Alianzas viejas se ponen a prueba mientras el destino del planeta pende de un hilo.",
                            Titulo = "Avengers Doomsday",
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            Clasificacion = "12+",
                            Director = "Renata Falcón",
                            Duracion = "2h 08m",
                            Etiqueta = "Tendencia",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Acción, Aventura, Superhéroes",
                            ImagenUrl = "https://assets.cinemark-core.com/5db771be04daec00076df3f5/vista/movies/6a22d1b9720d1d2a7f8d9a19/common/spiderman-nuevo-dia-109320-1780678232870",
                            Reparto = "Iker Salazar, Camila Rentería, Diego Guzmán",
                            Sinopsis = "Un joven héroe enmascarado debe proteger su ciudad de una nueva amenaza mientras intenta equilibrar su vida personal con la responsabilidad de llevar el traje. Acción trepidante entre los rascacielos y decisiones que lo marcarán para siempre.",
                            Titulo = "Spiderman",
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            Clasificacion = "15+",
                            Director = "Howard Steiner",
                            Duracion = "2h 15m",
                            Etiqueta = "Terror Pop",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Terror, Suspenso",
                            ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkmVRJ71XkUcnm_DAc2_d4_Iw9oX6bqu9lIY4Zz9a9ZlLOCDINM4dnX0zj&s=10",
                            Reparto = "Simon Wade, Charlotte Byrne, Milo Kagan",
                            Sinopsis = "En un pequeño pueblo, un grupo de niños se enfrenta a una entidad ancestral que se alimenta del miedo y toma la forma de sus peores pesadillas. Una historia de terror y amistad a partes iguales.",
                            Titulo = "It",
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            Clasificacion = "TP",
                            Director = "Estudios Costa Azul",
                            Duracion = "1h 47m",
                            Etiqueta = "Familiar",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Animación, Aventura, Familia",
                            ImagenUrl = "https://static.wikia.nocookie.net/disney/images/7/76/Moana_official_poster.jpg/revision/latest?cb=20160921035605&path-prefix=es",
                            Reparto = "Voces originales: Malia Kealoha, James Nuanez",
                            Sinopsis = "La hija de un jefe tribal se embarca en un viaje por el océano para salvar a su pueblo, guiada por la fuerza del mar y la ayuda de un semidiós algo arrogante. Aventura, música y descubrimiento personal en altamar.",
                            Titulo = "Moana",
                            Year = 2016
                        },
                        new
                        {
                            Id = 6,
                            Clasificacion = "12+",
                            Director = "Gary Feldstein",
                            Duracion = "1h 41m",
                            Etiqueta = "Comedia",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Comedia, Familia",
                            ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7zjfqxpuf0AHiQ-y2EvPuNku-JVcGZH2-_puckCF_sRdwbiKGdeF2tcqs&s=10",
                            Reparto = "Dennis Kohler, Marco Rubbio, Salma Trent",
                            Sinopsis = "Un grupo de amigos de toda la vida se reúne otra vez de vacaciones junto a sus familias, y el caos y las bromas están garantizados. Una comedia ligera sobre la amistad, la nostalgia y las vacaciones que nunca salen como se planean.",
                            Titulo = "Son como niños 2",
                            Year = 2013
                        },
                        new
                        {
                            Id = 7,
                            Clasificacion = "15+",
                            Director = "Wren Ashdown",
                            Duracion = "1h 38m",
                            Etiqueta = "Próximamente",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Terror, Suspenso",
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMjI5YTQ3YmItZjk1ZS00ZDBmLWJhZDMtNThhMDI5ZTRkMTcxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Reparto = "Ivy Callahan, Noah Prescott, Elias Vance",
                            Sinopsis = "Una familia se muda a una casa aislada con un pasado oscuro, sin saber que algo dentro de sus paredes lleva años esperando compañía. El terror psicológico se apodera de cada rincón de su nuevo hogar.",
                            Titulo = "The last house",
                            Year = 2026
                        },
                        new
                        {
                            Id = 8,
                            Clasificacion = "TP",
                            Director = "Rosa Delgadillo",
                            Duracion = "1h 31m",
                            Etiqueta = "Infantil",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Comedia, Familia",
                            ImagenUrl = "https://es.web.img2.acsta.net/medias/nmedia/18/68/79/58/19045139.jpg",
                            Reparto = "Voces originales: Andy García, Paz Vega",
                            Sinopsis = "Una pequeña chihuahua acostumbrada al lujo de Beverly Hills se pierde durante un viaje y debe encontrar el camino de regreso a casa junto a nuevos e inesperados amigos.",
                            Titulo = "Un chihuahua en Beverly Hills",
                            Year = 2008
                        },
                        new
                        {
                            Id = 9,
                            Clasificacion = "TP",
                            Director = "Alicia Montfort",
                            Duracion = "1h 45m",
                            Etiqueta = "Clásico",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Fantasía, Romance, Familia",
                            ImagenUrl = "https://es.web.img2.acsta.net/pictures/14/11/19/16/01/398307.jpg",
                            Reparto = "Elle Sinclair, Cate Ashworth, Robert Hale",
                            Sinopsis = "La versión en imagen real del clásico cuento de hadas: una joven bondadosa soporta el maltrato de su madrastra hasta que la magia y un baile real cambian su destino para siempre.",
                            Titulo = "Cenicienta",
                            Year = 2015
                        },
                        new
                        {
                            Id = 10,
                            Clasificacion = "TP",
                            Director = "Estudios Corona Real",
                            Duracion = "1h 40m",
                            Etiqueta = "Aventura Mágica",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Animación, Fantasía, Familia",
                            ImagenUrl = "https://es.web.img3.acsta.net/medias/nmedia/18/79/96/30/19541005.jpg",
                            Reparto = "Voces originales: Mandy Halloway, Zack Levinson",
                            Sinopsis = "Una princesa de cabello mágico y extraordinariamente largo escapa de la torre donde ha vivido encerrada toda su vida, junto a un carismático forajido, para descubrir por fin el mundo exterior.",
                            Titulo = "Rapunzel",
                            Year = 2010
                        },
                        new
                        {
                            Id = 11,
                            Clasificacion = "TP",
                            Director = "Estudios Ruta 66",
                            Duracion = "1h 57m",
                            Etiqueta = "Favorita",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Animación, Familia, Deportes",
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTg5NzY0MzA2MV5BMl5BanBnXkFtZTYwNDc3NTc2._V1_FMjpg_UX1000_.jpg",
                            Reparto = "Voces originales: Owen McQueen, Larry Hudson",
                            Sinopsis = "Un joven auto de carreras arrogante queda varado en un pequeño pueblo de la Ruta 66 y aprende, entre sus excéntricos habitantes, el verdadero significado de la amistad y la humildad.",
                            Titulo = "Cars: Una aventura sobre ruedas",
                            Year = 2006
                        },
                        new
                        {
                            Id = 12,
                            Clasificacion = "TP",
                            Director = "Estudios Lámpara Amarilla",
                            Duracion = "1h 21m",
                            Etiqueta = "Imperdible",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Animación, Familia, Aventura",
                            ImagenUrl = "https://es.web.img3.acsta.net/pictures/14/03/17/10/20/509771.jpg",
                            Reparto = "Voces originales: Tom Halbert, Timothy Allan",
                            Sinopsis = "Un vaquero de juguete ve amenazado su lugar como el favorito de su dueño con la llegada de una moderna figura de acción espacial. Juntos deberán aprender a trabajar en equipo para volver a casa.",
                            Titulo = "Toy Story",
                            Year = 1995
                        },
                        new
                        {
                            Id = 13,
                            Clasificacion = "TP",
                            Director = "Constance Fielding",
                            Duracion = "2h 09m",
                            Etiqueta = "Musical",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Fantasía, Romance, Musical",
                            ImagenUrl = "https://es.web.img3.acsta.net/pictures/17/01/09/09/56/256507.jpg",
                            Reparto = "Emmeline Rousse, Daniel Ashcombe, Ludovic Marchetti",
                            Sinopsis = "Versión en imagen real del clásico cuento: una joven inteligente y curiosa es retenida en un castillo encantado por una bestia con apariencia aterradora pero un corazón que aprende a abrirse.",
                            Titulo = "La bella y la bestia",
                            Year = 2017
                        },
                        new
                        {
                            Id = 14,
                            Clasificacion = "TP",
                            Director = "Estudios Pantano Dulce",
                            Duracion = "1h 37m",
                            Etiqueta = "Aclamada",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Animación, Fantasía, Musical",
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BOTE3YTExYTEtOTUxZC00OTM0LWJmYmItMDk5YjczNmIwNzA2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Reparto = "Voces originales: Anika Noni Rose, Bruno Campos",
                            Sinopsis = "Una joven trabajadora y soñadora de Nueva Orleans se convierte en rana tras un beso inesperado, y junto a un príncipe hechizado emprende una aventura mágica por los pantanos.",
                            Titulo = "La princesa y el sapo",
                            Year = 2009
                        },
                        new
                        {
                            Id = 15,
                            Clasificacion = "12+",
                            Director = "Rowena Ashcroft",
                            Duracion = "1h 37m",
                            Etiqueta = "Fantasía",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Fantasía, Aventura",
                            ImagenUrl = "https://es.web.img3.acsta.net/pictures/14/03/11/09/33/450247.jpg",
                            Reparto = "Ainsley Deveraux, Elle Fanshawe, Sam Riordan",
                            Sinopsis = "La verdadera historia detrás del hada oscura: una traición en su juventud despierta una maldición que lanza sobre un reino entero, hasta que una niña inocente pone a prueba su corazón endurecido.",
                            Titulo = "Malefica",
                            Year = 2014
                        },
                        new
                        {
                            Id = 16,
                            Clasificacion = "12+",
                            Director = "Rowena Ashcroft",
                            Duracion = "1h 59m",
                            Etiqueta = "Secuela",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Fantasía, Aventura",
                            ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/5/56/MLFCDMCartel.jpg/revision/latest?cb=20190927034818&path-prefix=es",
                            Reparto = "Ainsley Deveraux, Elle Fanshawe, Marguerite Colt",
                            Sinopsis = "Con el compromiso real en puerta, viejas tensiones entre humanos y criaturas mágicas resurgen, obligando al hada oscura a decidir hasta dónde llegar para proteger a quienes ama.",
                            Titulo = "Malefica 2",
                            Year = 2019
                        },
                        new
                        {
                            Id = 17,
                            Clasificacion = "TP",
                            Director = "Estudios Arrecife de Coral",
                            Duracion = "1h 23m",
                            Etiqueta = "Clásico Animado",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Animación, Fantasía, Musical",
                            ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/6/6f/28a.jpg/revision/latest/scale-to-width-down/1200?cb=20200812013209&path-prefix=es",
                            Reparto = "Voces originales: Jodi Benson, Pat Carroll",
                            Sinopsis = "Una joven sirena fascinada por el mundo humano hace un trato peligroso con una bruja del mar a cambio de piernas y la oportunidad de vivir en tierra firme.",
                            Titulo = "La sirenita",
                            Year = 1989
                        },
                        new
                        {
                            Id = 18,
                            Clasificacion = "TP",
                            Director = "Estudios Arrecife de Coral",
                            Duracion = "1h 15m",
                            Etiqueta = "Próximamente",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Animación, Fantasía, Musical",
                            ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/1/1c/La_Sirenita_2.jpg/revision/latest?cb=20091112103319&path-prefix=es",
                            Reparto = "Voces originales: Jodi Benson, Tara Strong",
                            Sinopsis = "Años después de dejar el mar, la hija de la sirena debe redescubrir su propia conexión con el océano cuando un viejo peligro familiar regresa a amenazar su hogar en tierra.",
                            Titulo = "La sirenita 2",
                            Year = 2026
                        },
                        new
                        {
                            Id = 19,
                            Clasificacion = "15+",
                            Director = "Marcus Thorne",
                            Duracion = "1h 30m",
                            Etiqueta = "Suspenso",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Terror, Suspenso",
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BYzY2ZjM0NTgtNDc3OS00YmQwLTlkN2YtMmRmMDAxMmM0NTliXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Reparto = "Ellery Voss, Grant Halliwell, Priya Anand",
                            Sinopsis = "En una casa donde el más mínimo sonido puede significar el fin, una familia debe aprender a comunicarse en absoluto silencio para sobrevivir a una presencia que acecha en la oscuridad.",
                            Titulo = "The silent",
                            Year = 2019
                        },
                        new
                        {
                            Id = 20,
                            Clasificacion = "15+",
                            Director = "Marcus Thorne",
                            Duracion = "1h 39m",
                            Etiqueta = "Éxito",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Terror, Suspenso, Ciencia ficción",
                            ImagenUrl = "https://m.media-amazon.com/images/S/pv-target-images/450fc3671402b95549e29af286cf9c6c4aa439e2a2399adbde570f2970c6092a._UR2000,3000_.jpg",
                            Reparto = "Grant Halliwell, Priya Anand, Owen Castellanos",
                            Sinopsis = "El relato de las primeras horas de una invasión silenciosa: una ciudad entera aprende, de la forma más brutal, que hacer ruido puede costarle la vida a cualquiera.",
                            Titulo = "Un lugar en silencio dia 1",
                            Year = 2018
                        },
                        new
                        {
                            Id = 21,
                            Clasificacion = "15+",
                            Director = "Selene Kowalski",
                            Duracion = "1h 46m",
                            Etiqueta = "Novedad",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Suspenso, Drama",
                            ImagenUrl = "https://pics.filmaffinity.com/don_t_say_good_luck-469823819-large.jpg",
                            Reparto = "Nadia Ferro, Julián Vasconcelos, Marina Estep",
                            Sinopsis = "Una racha de sucesos cada vez más inquietantes convence a una mujer de que la suerte, buena o mala, se puede heredar como una maldición familiar que ahora le toca romper.",
                            Titulo = "No se desea buena suerte",
                            Year = 2026
                        },
                        new
                        {
                            Id = 22,
                            Clasificacion = "15+",
                            Director = "Ibrahim Castell",
                            Duracion = "1h 52m",
                            Etiqueta = "Policial",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Suspenso, Drama, Crimen",
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BOGJkNjBkNTUtYWM2OC00MDJiLWE0ZjctMmMxMjE1ODMxMzQxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
                            Reparto = "Renata Ibarra, Tomás Aldunate, Greta Solheim",
                            Sinopsis = "Un detective obsesionado con un caso sin resolver se acerca peligrosamente a la verdad, solo para descubrir que atrapar al culpable puede costarle todo lo que ama.",
                            Titulo = "La captura",
                            Year = 2026
                        },
                        new
                        {
                            Id = 23,
                            Clasificacion = "TP",
                            Director = "Priscilla Nkemelu",
                            Duracion = "1h 35m",
                            Etiqueta = "Romance",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Comedia, Romance",
                            ImagenUrl = "https://static.wikia.nocookie.net/doblaje/images/e/e9/LaNuevaCenicienta_Poster.png/revision/latest?cb=20190818235855&path-prefix=es",
                            Reparto = "Holly Marchbanks, Cody Trentham, Bianca Suárez",
                            Sinopsis = "Una estudiante que trabaja en el restaurante familiar sueña con salir de su pequeño pueblo, y encuentra en un chat anónimo con un compañero de escuela la esperanza de un futuro distinto.",
                            Titulo = "La nueva cenicienta",
                            Year = 2004
                        },
                        new
                        {
                            Id = 24,
                            Clasificacion = "TP",
                            Director = "Priscilla Nkemelu",
                            Duracion = "1h 30m",
                            Etiqueta = "Juvenil",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Comedia, Romance",
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTUwNDAzMzIxOF5BMl5BanBnXkFtZTgwNTU1NzAwNzE@._V1_FMjpg_UX1000_.jpg",
                            Reparto = "Holly Marchbanks, Devon Ashworth, Bianca Suárez",
                            Sinopsis = "Una nueva generación revive el cuento moderno de Cenicienta: una chica trabajadora usa un alias en línea para perseguir sus sueños, sin imaginar a quién va a encontrar del otro lado.",
                            Titulo = "La nueva cenicienta 2",
                            Year = 2008
                        },
                        new
                        {
                            Id = 25,
                            Clasificacion = "TP",
                            Director = "Desmond Aldwych",
                            Duracion = "1h 55m",
                            Etiqueta = "Imperdible",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Fantasía, Familia, Musical",
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTAxMGFjODItYTliNy00NjQyLTlkM2MtYWY5YzVmYjk5OGFiXkEyXkFqcGc@._V1_.jpg",
                            Reparto = "Warrick Feathering, Ida Loncar, Percy Whitmore",
                            Sinopsis = "Un niño de escasos recursos gana un boleto dorado para visitar la fábrica de chocolates más misteriosa del mundo, dirigida por un excéntrico e impredecible chocolatero.",
                            Titulo = "Charlie y la fábrica de chocolate",
                            Year = 2005
                        },
                        new
                        {
                            Id = 26,
                            Clasificacion = "TP",
                            Director = "Documental Colectivo Sur",
                            Duracion = "1h 47m",
                            Etiqueta = "Documental",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Documental, Biografía, Deportes",
                            ImagenUrl = "https://hips.hearstapps.com/hmg-prod/images/pele-dcumental-netflix-esquire2-1613895136.jpg",
                            Reparto = "Con la participación de figuras del fútbol mundial",
                            Sinopsis = "Un repaso documental a la vida de uno de los futbolistas más influyentes de la historia, desde su infancia humilde hasta convertirse en leyenda del deporte a nivel global.",
                            Titulo = "Pelé",
                            Year = 2021
                        },
                        new
                        {
                            Id = 27,
                            Clasificacion = "TP",
                            Director = "Winona Halbrook",
                            Duracion = "1h 32m",
                            Etiqueta = "Comedia",
                            Formatos = "HD, 5.1, CC",
                            Genero = "Comedia, Familia",
                            ImagenUrl = "https://m.media-amazon.com/images/M/MV5BMTIwMDQyNjQzNl5BMl5BanBnXkFtZTcwMjEwODI0MQ@@._V1_.jpg",
                            Reparto = "Desmond Pratchett, Ainsley Marek, Cora Bellweather",
                            Sinopsis = "Cuando una familia se muda a una nueva ciudad, su casa parece tener vida propia y decide literalmente ponerlo todo patas arriba, generando una serie de enredos tan caóticos como divertidos.",
                            Titulo = "Una casa patas arriba",
                            Year = 2007
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
