// <auto-generated />
using JhaylaPlusAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JhaylaPlusAPI.Migrations.UsuariosDb
{
    [DbContext(typeof(UsuariosDbContext))]
    [Migration("20260903190500_AgregarFavoritos")]
    partial class AgregarFavoritos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JhaylaPlusAPI.Models.Favorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "PeliculaId")
                        .IsUnique();

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("JhaylaPlusAPI.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Nuñez",
                            Contraseña = "1234",
                            Correo = "addununeznunezavila@gmail.com",
                            Nombre = "Addu"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Frias",
                            Contraseña = "1234",
                            Correo = "luis.frias@gmail.com",
                            Nombre = "Luis"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Rincones",
                            Contraseña = "1234",
                            Correo = "andres.rincones@gmail.com",
                            Nombre = "Andres"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Florez",
                            Contraseña = "1234",
                            Correo = "rafael.florez@gmail.com",
                            Nombre = "Rafael"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
